[book]
authors = ["Anthony Whalley"]
language = "en"
multilingual = false
src = "src"
title = "Core Dumps Information"


[output.html]
default-theme="light"
git-repository-url="https://github.com/no9/coredumps.info"
